#!/bin/sh

# Slackware build script for libsystemd0

# Copyright 2021 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=libsystemd0
SRCNAM=libsystemd-dev
VERSION=249.4
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

WD=$PWD; mkdir -p $PRGNAM; chown -R 1000:users $PRGNAM; cd $PRGNAM 

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK1=http://ftp.br.debian.org/debian/pool/main/s/systemd/libsystemd0_249.4-1_amd64.deb
LINK2=http://ftp.br.debian.org/debian/pool/main/s/systemd/libsystemd-dev_249.4-1_amd64.deb

set -e
wget -c $LINK1 $LINK2
rm -rf $PKG
mkdir -p $PKG/{install,usr/{doc/$PRGNAM-$VERSION,lib64}}
cd $PKG; ar p $CWD/${PRGNAM}_${VERSION}*_amd64.deb data.tar.xz | tar xJv
ar p $CWD/${SRCNAM}_${VERSION}*_amd64.deb data.tar.xz | tar xJv

mv usr/lib/x86_64-linux-gnu/libsystemd.so.0.32.0 $PKG/usr/lib64/
mv usr/lib/x86_64-linux-gnu/pkgconfig $PKG/usr/lib64/

ln -s /usr/lib64/libsystemd.so.0.32.0 $PKG/usr/lib64/libsystemd.so.0
ln -s /usr/lib64/libsystemd.so.0.32.0 $PKG/usr/lib64/libsystemd.so

mv usr/share/doc/{$PRGNAM,$SRCNAM} $PKG/usr/doc/$PRGNAM-$VERSION
mv usr/share/man $PKG/usr

rm -r $PKG/usr/{share,lib}

chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

echo "           |-----handy-ruler------------------------------------------------------|
libsystemd0: libsystemd0 (library for systemd)
libsystemd0:
libsystemd0: systemd is a suite of basic building blocks for a Linux system.
libsystemd0:
libsystemd0:
libsystemd0:
libsystemd0:
libsystemd0:
libsystemd0:
libsystemd0:
libsystemd0:" > $PKG/install/slack-desc

/sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	[ -e "../Exclamation.mp3" ] && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY mplayer $WD/Exclamation.mp3 > /dev/null
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
