#!/bin/sh
# Dependencies

# Slackware build script for wxGTK3

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=wxGTK3
SRCNAM=wxWidgets
VERSION=3.0.5.1
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}
NUMJOBS=${NUMJOBS:-" -j$(nproc) "}

case "$( uname -m )" in
	i?86) ARCH=i586 ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://github.com/wxWidgets/wxWidgets/archive/v3.0.5.1/wxWidgets-3.0.5.1.tar.gz

if [ "$ARCH" = "i586" ]; then
	SLKCFLAGS="-O2 -march=i586 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
	SLKCFLAGS="-O2 -march=i686 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "aarch64" ]; then
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX="64"
elif [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-O2 -fPIC"
	LIBDIRSUFFIX="64"
else
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX=""
fi

set -e
wget -c $LINK
rm -rf $PKG $TMP/$SRCNAM-$VERSION
mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; tar xvf $CWD/$SRCNAM-$VERSION.tar.?z*
cd $SRCNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --localstatedir=/var \
  --sysconfdir=/etc \
  --disable-precomp-headers \
  --disable-shared \
  --disable-stl \
  --enable-graphics_ctx \
  --enable-mediactrl \
  --enable-plugins \
  --enable-unicode \
  --enable-webview \
  --with-gtk=2 \
  --with-opengl \
  --with-libpng=sys \
  --with-libxpm=sys \
  --with-libjpeg=sys \
  --with-libtiff=sys \
  --program-prefix= \
  --program-suffix= \
  --build=$ARCH-slackware-linux
make $NUMJOBS; make -C locale allmo; make install DESTDIR=$PKG

rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
mv $PKG/usr/bin/wx-config{,-gtk2}

make clean
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --localstatedir=/var \
  --sysconfdir=/etc \
  --disable-precomp-headers \
  --disable-shared \
  --disable-stl \
  --enable-graphics_ctx \
  --enable-mediactrl \
  --enable-plugins \
  --enable-unicode \
  --with-gtk=3 \
  --with-opengl \
  --program-prefix= \
  --program-suffix= \
  --with-sdl \
  --with-libmspack \
  --with-libpng=sys \
  --with-libxpm=sys \
  --with-libjpeg=sys \
  --with-libtiff=sys \
  --build=$ARCH-slackware-linux
make $NUMJOBS; make -C locale allmo; make install DESTDIR=$PKG

rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
mv $PKG/usr/bin/wx-config{,-gtk3}

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
find $PKG | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs strip -g 2> /dev/null || true
cp -a docs/* $PKG/usr/doc/$PRGNAM-$VERSION
ln -fs /usr/lib${LIBDIRSUFFIX}/wx/config/gtk2-unicode-static-3.0 $PKG/usr/bin/wx-config

echo "      |-----handy-ruler------------------------------------------------------|
wxGTK3: wxGTK3 (cross-platform GUI toolkit)
wxGTK3:
wxGTK3: wxGTK3 is part of wxWidgets, a cross-platform API for writing GUI
wxGTK3: applications on multiple platforms that still utilize the native
wxGTK3: platform's controls and utilities.
wxGTK3:
wxGTK3: http://wxwidgets.org
wxGTK3:
wxGTK3:
wxGTK3:
wxGTK3:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$SRCNAM-$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
