#!/bin/sh
# Software

# Slackware build script for correo

# Copyright 2021 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=Correo
VERSION=1.0.6
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

WD=$PWD; mkdir -p $PRGNAM; chown -R 1000:users $PRGNAM; cd $PRGNAM 

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK1=https://github.com/mxnt10/Slackware15-Reposity/releases/download/Release/Correo-1.0.6.tar.xz

set -e
wget -c $LINK1
rm -rf $PKG $TMP
mkdir -p $TMP $PKG/{install,opt,usr/{lib64/Correo,bin,share/{applications,pixmaps}}}
cd $PKG/opt; tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cd $PKG
chmod +x opt/$PRGNAM-$VERSION/$PRGNAM
ln -s /opt/$PRGNAM-$VERSION/$PRGNAM $PKG/usr/bin/correo
cp -a opt/$PRGNAM-$VERSION/resources/app/res/correo.png $PKG/usr/share/pixmaps

echo "[Desktop Entry]
Name=Correo
GenericName=Correo
Comment=Gmail Client in Tray
Icon=correo
Exec=correo
Terminal=false
Type=Application
Categories=Network;" > $PKG/usr/share/applications/$PRGNAM.desktop

echo "      |-----handy-ruler------------------------------------------------------|
Correo: Correo (A menubar/taskbar Gmail App based on Electron)
Correo:
Correo: Runs Gmail right from the Taskbar (in Windows) or from the
Correo: Menubar (in macOS).
Correo: Remains active in the tray for quick usage.
Correo: Uses Gmail's UI for mobile so it's best to use within
Correo: menubar/taskbar.
Correo:
Correo: https://www.electronjs.org/apps/correo
Correo:
Correo:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	[ -e "../Exclamation.mp3" ] && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY mplayer $WD/Exclamation.mp3 > /dev/null
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
